apiVersion: v1
kind: ConfigMap
metadata:
  name: post-service-configmap
  namespace: production
data:
  auth_service_url: http://auth-internal-service.production.svc.cluster.local:8888
  otel-service-name: production-post-service
  otel-exporter-insecure: "true"
  otel-exporter-endpoint: http://jaeger.observability.svc.cluster.local:4317
  otel-metrics-exporter: none
  otel-logs-exporter: none