apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
  namespace: staging
data:
  algorithm: "HS256"
  access_token_expire_minutes: "30"
  otel-service-name: staging-auth-service
  otel-exporter-insecure: "true"
  otel-exporter-endpoint: http://jaeger.observability.svc.cluster.local:4317
  otel-metrics-exporter: none
  otel-logs-exporter: none