apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-service-configmap
  namespace: staging
data:
  auth_service_url: http://auth-internal-service.staging.svc.cluster.local:8000
  post_service_url: http://post-internal-service.staging.svc.cluster.local:8000