apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: staging
type: Opaque
data:
  secret-key: YmEzY2YzMThhMGIxMWNmNzYzYzRmYzBhODUzOTQ2ZWM0MGQ0MzY0N2RkMmE1MjI1N2ZjMjM0OWM1YmM1N2Q3MA==